# my first dockerfile!!
# i learned this from youtube
FROM python:3.9

# copy the file
COPY server.py /app/server.py

# go to folder
WORKDIR /app

# expose port (i think render needs this??)
EXPOSE 10000

# run it
CMD ["python", "server.py"]
